### ISSUE TITLE
Suggestion: Title, Subtitle, and Icon

### ISSUE THREAD

**Issue by vutran** [adnasa/dext-wikipedia-plugin#1]
pageterms: /w/api.php?action=query&format=json&prop=pageterms&list=&titles=Albert+Einstein
- Title can be set as the entries' own title
- Subtitle can be mapped to the `pageterms` `description`.

pageimages: /w/api.php?action=query&format=json&prop=pageimages&list=&titles=Albert+Einstein

A thumbnail can be retrieved via the `pageimages` prop.

**Comment by adnasa** [comment]
thanks @vutran, will take a look whenever I can.

**Comment by adnasa** [comment]
@vutran this is fixed now 8fd963a

closing..
